package org.beehive.jllm.backend.tornado.kernels;

import uk.ac.manchester.tornado.api.KernelContext;
import uk.ac.manchester.tornado.api.annotations.Parallel;
import uk.ac.manchester.tornado.api.math.TornadoMath;
import uk.ac.manchester.tornado.api.types.arrays.FloatArray;
import uk.ac.manchester.tornado.api.types.arrays.HalfFloatArray;
import uk.ac.manchester.tornado.api.types.arrays.IntArray;
import uk.ac.manchester.tornado.api.types.vectors.Half2;

/**
 * Llama single-token KV kernels that address the cache through a block table.
 *
 * <p>Each method here is the {@code Paged} twin of the identically named kernel in {@link
 * TransformerComputeKernelsLayered}, with <b>one</b> difference: the KV index. Everything else —
 * tiling, the online-softmax arithmetic, the barriers, the loop structure, even where in the loop
 * nest the offset is computed — is character-for-character the legacy body, so a golden that moves
 * is an addressing bug and nothing else.
 *
 * <p>Addressing is defined once, in {@link KvBlockAddress}. This file must not acquire kernel
 * mathematics of its own; if a numerics change is wanted, it belongs in the legacy kernel first and
 * is mirrored here.
 *
 * <p><b>Generated by transformation, reviewed by hand.</b> The bodies were extracted from {@code
 * TransformerComputeKernelsLayered} and rewritten mechanically, so a diff against the legacy kernel
 * is the intended way to review them.
 */
public class TransformerPagedKvKernels {

    public TransformerPagedKvKernels() {}

    public static void ropeRotationWithCacheCopyPrecomputedPaged(
            KernelContext context,
            IntArray positionHolder,
            FloatArray sq,
            FloatArray sk,
            FloatArray sv,
            FloatArray keyCache,
            FloatArray valueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        int i = context.globalIdx * 2;
        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);

        if (i + 1 < sq.getSize()) {
            int head_dim = i % headSize;
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q
            float v0q = sq.get(i);
            float v1q = sq.get(i + 1);
            sq.set(i, v0q * fcr - v1q * fci);
            sq.set(i + 1, v0q * fci + v1q * fcr);

            // Rotate K AND write to cache
            if (i + 1 < kvDim) {
                float v0k = sk.get(i);
                float v1k = sk.get(i + 1);
                float rotated0 = v0k * fcr - v1k * fci;
                float rotated1 = v0k * fci + v1k * fcr;

                sk.set(i, rotated0);
                sk.set(i + 1, rotated1);

                int cacheOffset =
                        KvBlockAddress.offset(
                                blockTable,
                                slot,
                                pos,
                                KvBlockAddress.layerOffset(layer, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                keyCache.set(cacheOffset + i, rotated0);
                keyCache.set(cacheOffset + i + 1, rotated1);

                valueCache.set(cacheOffset + i, sv.get(i));
                valueCache.set(cacheOffset + i + 1, sv.get(i + 1));
            }
        }
    }

    public static void ropeRotationWithCacheCopyPrecomputedFP16Paged(
            KernelContext context,
            IntArray positionHolder,
            FloatArray sq,
            FloatArray sk,
            FloatArray sv,
            HalfFloatArray keyCache,
            HalfFloatArray valueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        int i = context.globalIdx * 2;
        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);

        if (i + 1 < sq.getSize()) {
            // Frequencies come from the model's precomputed tables, as in the FP32 twin
            // ropeRotationWithCacheCopyPrecomputed; a base baked into the kernel was wrong
            // for Llama-3.2 (50000 vs the declared 500000).
            int head_dim = i % headSize;
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q
            float v0q = sq.get(i);
            float v1q = sq.get(i + 1);
            sq.set(i, v0q * fcr - v1q * fci);
            sq.set(i + 1, v0q * fci + v1q * fcr);

            // Rotate K AND write to cache (only for kvDim elements)
            if (i + 1 < kvDim) {
                float v0k = sk.get(i);
                float v1k = sk.get(i + 1);
                float rotated0 = v0k * fcr - v1k * fci;
                float rotated1 = v0k * fci + v1k * fcr;

                sk.set(i, rotated0);
                sk.set(i + 1, rotated1);

                int cacheOffset =
                        KvBlockAddress.offset(
                                blockTable,
                                slot,
                                pos,
                                KvBlockAddress.layerOffset(layer, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                keyCache.setHalf2(cacheOffset + i, Half2.fromFloats(rotated0, rotated1));
                valueCache.setHalf2(cacheOffset + i, Half2.fromFloats(sv.get(i), sv.get(i + 1)));
            }
        }
    }

    public static void processHeadsFlashAttentionPaged(
            KernelContext context,
            FloatArray q,
            FloatArray key_cache,
            FloatArray value_cache,
            FloatArray xb,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        // Thread and workgroup information
        int tid = context.localIdx;
        int h = context.groupIdx; // Each workgroup processes one head
        int localSize = context.localGroupSizeX;

        // Early exit if this workgroup is beyond our head count
        // This relies on the kernel being launched with nHeads workgroups.
        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_SIZE_C = 16;

        // Allocate shared memory for tiled computation
        float[] q_shared = context.allocateFloatLocalArray(headSize);
        float[] k_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] v_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] s_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C);
        float[] shared_tile_max_holder =
                context.allocateFloatLocalArray(1); // FIX: For broadcasting tile max

        // Thread-local accumulators for online softmax
        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;

        // Thread-local output accumulation
        float[] output = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            output[i] = 0.0f;
        }

        // Load query vector into shared memory
        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }

        context.localBarrier();

        // Process sequence in tiles
        for (int tileC = 0; tileC <= pos; tileC += BLOCK_SIZE_C) {
            int tileEnd = Math.min(tileC + BLOCK_SIZE_C - 1, pos);

            // Load key and value vectors for this tile
            // Each thread loads a portion of the K and V vectors for the tile
            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int k_v_idx_in_tile = tIdxInSeq - tileC; // 0, 1, 2, or 3 for this tile
                int tileMemOffset = k_v_idx_in_tile * headSize;
                // The block walk depends on the position, not on d, so it is computed once
                // per position. Keeping it inside the loop — where the legacy line that
                // computed loff + pos*kvDim + d sat — costs a table load and an integer
                // divide per element, which measured -7.3% on Qwen2 Q8_0.
                int kvBase =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tIdxInSeq,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize;
                for (int d = 0; d < headSize; d++) {
                    k_tile[tileMemOffset + d] = key_cache.get(kvBase + d);
                    v_tile[tileMemOffset + d] = value_cache.get(kvBase + d);
                }
            }

            context.localBarrier();

            // Compute attention scores for this tile
            // Each thread computes one score for the tile
            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int score_idx_in_tile = tIdxInSeq - tileC; // 0, 1, 2, or 3 for this tile

                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += q_shared[d] * k_tile[score_idx_in_tile * headSize + d];
                }
                score /= TornadoMath.sqrt(headSize);
                s_tile[score_idx_in_tile] = score;
            }

            context.localBarrier();

            // Find max score in this tile (all threads compute it redundantly over the small
            // s_tile)
            float tileLocalMax = Float.NEGATIVE_INFINITY;
            for (int i = 0; i <= tileEnd - tileC; i++) { // Iterate over valid scores in s_tile
                if (s_tile[i] > tileLocalMax) {
                    tileLocalMax = s_tile[i];
                }
            }

            // Broadcast max to all threads via shared memory
            if (tid == 0) {
                shared_tile_max_holder[0] = tileLocalMax; // FIX: Use dedicated holder
            }
            context.localBarrier();
            float currentTileMax = shared_tile_max_holder[0]; // FIX: Read from dedicated holder

            // Determine if we need to rescale previous results
            float newMax = Math.max(maxScore, currentTileMax);
            if (newMax != maxScore && maxScore != Float.NEGATIVE_INFINITY) {
                float scale = TornadoMath.exp(maxScore - newMax);
                sumExp *= scale;
                for (int d = 0; d < headSize; d++) {
                    output[d] *= scale;
                }
            }
            maxScore = newMax;

            // Process each key-value pair using original scores from s_tile
            // All threads iterate over all scores in the current tile
            for (int t_idx_in_s_tile = 0; t_idx_in_s_tile <= tileEnd - tileC; t_idx_in_s_tile++) {
                // s_tile[t_idx_in_s_tile] now correctly refers to the original score
                float expScore = TornadoMath.exp(s_tile[t_idx_in_s_tile] - maxScore);
                sumExp += expScore;

                for (int d = 0; d < headSize; d++) {
                    output[d] += expScore * v_tile[t_idx_in_s_tile * headSize + d];
                }
            }
            context.localBarrier(); // Ensure all threads finish with s_tile, k_tile, v_tile before
            // next tile load
        }

        // Normalize and write final results
        float normFactor =
                (sumExp > 0.0f)
                        ? (1.0f / sumExp)
                        : 0.0f; // Avoid division by zero, return 0 if sumExp is 0
        for (int d = tid; d < headSize; d += localSize) {
            xb.set(h * headSize + d, output[d] * normFactor);
        }
    }

    public static void processHeadsFlashAttentionFP16Paged(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray xb,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        int tid = context.localIdx;
        int h = context.groupIdx;
        int localSize = context.localGroupSizeX;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_SIZE_C = 16;

        float[] q_shared = context.allocateFloatLocalArray(headSize);
        float[] k_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] v_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] s_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C);
        float[] shared_tile_max_holder = context.allocateFloatLocalArray(1);

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;

        float[] output = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            output[i] = 0.0f;
        }

        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }

        context.localBarrier();

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_SIZE_C) {
            int tileEnd = Math.min(tileC + BLOCK_SIZE_C - 1, pos);

            // Packed 32-bit FP16 pair loads; expand to FP32 tiles in shared memory.
            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int tileMemOffset = (tIdxInSeq - tileC) * headSize;
                int kvBase =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tIdxInSeq,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize;
                for (int d = 0; d < headSize; d += 2) {
                    Half2 kPair = key_cache.getHalf2(kvBase + d);
                    Half2 vPair = value_cache.getHalf2(kvBase + d);
                    k_tile[tileMemOffset + d] = Half2.lowFloat(kPair);
                    k_tile[tileMemOffset + d + 1] = Half2.highFloat(kPair);
                    v_tile[tileMemOffset + d] = Half2.lowFloat(vPair);
                    v_tile[tileMemOffset + d + 1] = Half2.highFloat(vPair);
                }
            }

            context.localBarrier();

            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int score_idx_in_tile = tIdxInSeq - tileC;

                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += q_shared[d] * k_tile[score_idx_in_tile * headSize + d];
                }
                score /= TornadoMath.sqrt(headSize);
                s_tile[score_idx_in_tile] = score;
            }

            context.localBarrier();

            float tileLocalMax = Float.NEGATIVE_INFINITY;
            for (int i = 0; i <= tileEnd - tileC; i++) {
                if (s_tile[i] > tileLocalMax) {
                    tileLocalMax = s_tile[i];
                }
            }

            if (tid == 0) {
                shared_tile_max_holder[0] = tileLocalMax;
            }
            context.localBarrier();
            float currentTileMax = shared_tile_max_holder[0];

            float newMax = Math.max(maxScore, currentTileMax);
            if (newMax != maxScore && maxScore != Float.NEGATIVE_INFINITY) {
                float scale = TornadoMath.exp(maxScore - newMax);
                sumExp *= scale;
                for (int d = 0; d < headSize; d++) {
                    output[d] *= scale;
                }
            }
            maxScore = newMax;

            for (int t_idx_in_s_tile = 0; t_idx_in_s_tile <= tileEnd - tileC; t_idx_in_s_tile++) {
                float expScore = TornadoMath.exp(s_tile[t_idx_in_s_tile] - maxScore);
                sumExp += expScore;

                for (int d = 0; d < headSize; d++) {
                    output[d] += expScore * v_tile[t_idx_in_s_tile * headSize + d];
                }
            }
            context.localBarrier();
        }

        float normFactor = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        for (int d = tid; d < headSize; d += localSize) {
            xb.set(h * headSize + d, output[d] * normFactor);
        }
    }

    public static void processHeadsFlashAttentionFP16ScalarPaged(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray xb,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        int tid = context.localIdx;
        int h = context.groupIdx;
        int localSize = context.localGroupSizeX;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_SIZE_C = 16;

        float[] q_shared = context.allocateFloatLocalArray(headSize);
        float[] k_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] v_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C * headSize);
        float[] s_tile = context.allocateFloatLocalArray(BLOCK_SIZE_C);
        float[] shared_tile_max_holder = context.allocateFloatLocalArray(1);

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;

        float[] output = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            output[i] = 0.0f;
        }

        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }

        context.localBarrier();

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_SIZE_C) {
            int tileEnd = Math.min(tileC + BLOCK_SIZE_C - 1, pos);

            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int tileMemOffset = (tIdxInSeq - tileC) * headSize;
                int kvBase =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tIdxInSeq,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize;
                for (int d = 0; d < headSize; d++) {
                    k_tile[tileMemOffset + d] = key_cache.get(kvBase + d).getFloat32();
                    v_tile[tileMemOffset + d] = value_cache.get(kvBase + d).getFloat32();
                }
            }

            context.localBarrier();

            for (int tIdxInSeq = tileC + tid; tIdxInSeq <= tileEnd; tIdxInSeq += localSize) {
                int score_idx_in_tile = tIdxInSeq - tileC;

                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += q_shared[d] * k_tile[score_idx_in_tile * headSize + d];
                }
                score /= TornadoMath.sqrt(headSize);
                s_tile[score_idx_in_tile] = score;
            }

            context.localBarrier();

            float tileLocalMax = Float.NEGATIVE_INFINITY;
            for (int i = 0; i <= tileEnd - tileC; i++) {
                if (s_tile[i] > tileLocalMax) {
                    tileLocalMax = s_tile[i];
                }
            }

            if (tid == 0) {
                shared_tile_max_holder[0] = tileLocalMax;
            }
            context.localBarrier();
            float currentTileMax = shared_tile_max_holder[0];

            float newMax = Math.max(maxScore, currentTileMax);
            if (newMax != maxScore && maxScore != Float.NEGATIVE_INFINITY) {
                float scale = TornadoMath.exp(maxScore - newMax);
                sumExp *= scale;
                for (int d = 0; d < headSize; d++) {
                    output[d] *= scale;
                }
            }
            maxScore = newMax;

            for (int t_idx_in_s_tile = 0; t_idx_in_s_tile <= tileEnd - tileC; t_idx_in_s_tile++) {
                float expScore = TornadoMath.exp(s_tile[t_idx_in_s_tile] - maxScore);
                sumExp += expScore;

                for (int d = 0; d < headSize; d++) {
                    output[d] += expScore * v_tile[t_idx_in_s_tile * headSize + d];
                }
            }
            context.localBarrier();
        }

        float normFactor = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        for (int d = tid; d < headSize; d += localSize) {
            xb.set(h * headSize + d, output[d] * normFactor);
        }
    }

    public static void processHeadsFlashAttentionSplitKVPaged(
            KernelContext context,
            FloatArray q,
            FloatArray key_cache,
            FloatArray value_cache,
            FloatArray att,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int nSplits) {

        final int MAX_HEAD_SIZE = 128;
        final int MAX_LOCAL_SIZE = 64;

        int tid = context.localIdx;
        int g = context.groupIdx; // 0 .. nHeads*nSplits - 1
        int localSize = context.localGroupSizeX;
        int h = g / nSplits;
        int s = g % nSplits;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int seqLen = pos + 1;
        int chunk = (seqLen + nSplits - 1) / nSplits;
        int startPos = s * chunk;
        int endPos = Math.min(startPos + chunk, seqLen); // exclusive

        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        float invSqrt = 1.0f / TornadoMath.sqrt(headSize);

        float[] q_shared = context.allocateFloatLocalArray(MAX_HEAD_SIZE);
        float[] accShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE * MAX_HEAD_SIZE);
        float[] mShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] lShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] corrShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] bcast = context.allocateFloatLocalArray(1);

        // Per-head region within att, COMPACT layout (stride nSplits*(headSize+2)):
        // [nSplits*headSize partial outputs][nSplits block maxima][nSplits block sums]. A
        // contextLength stride here would scatter writes at large offsets that TornadoVM fails to
        // sync between the two tasks.
        int headBase = h * nSplits * (headSize + 2);
        int outBase = headBase + s * headSize;
        int mBase = headBase + nSplits * headSize;
        int lBase = mBase + nSplits;

        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }
        int rowBase = tid * headSize;
        for (int d = 0; d < headSize; d++) {
            accShared[rowBase + d] = 0.0f;
        }
        context.localBarrier();

        // Strided scan over this split's position chunk (no barriers).
        float m = Float.NEGATIVE_INFINITY;
        float l = 0.0f;
        for (int p = startPos + tid; p < endPos; p += localSize) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, p, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;
            float score = 0.0f;
            for (int d = 0; d < headSize; d++) {
                score += q_shared[d] * key_cache.get(base + d);
            }
            score *= invSqrt;
            float newM = Math.max(m, score);
            float corr = (m == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(m - newM);
            float e = TornadoMath.exp(score - newM);
            for (int d = 0; d < headSize; d++) {
                accShared[rowBase + d] =
                        accShared[rowBase + d] * corr + e * value_cache.get(base + d);
            }
            l = l * corr + e;
            m = newM;
        }
        mShared[tid] = m;
        lShared[tid] = l;
        context.localBarrier();

        // Block max.
        if (tid == 0) {
            float blockMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < localSize; t++) {
                if (mShared[t] > blockMax) {
                    blockMax = mShared[t];
                }
            }
            bcast[0] = blockMax;
        }
        context.localBarrier();
        float M = bcast[0];

        corrShared[tid] =
                (mShared[tid] == Float.NEGATIVE_INFINITY)
                        ? 0.0f
                        : TornadoMath.exp(mShared[tid] - M);
        context.localBarrier();

        // Block sum L = Σ_t l_t · corr_t.
        if (tid == 0) {
            float blockSum = 0.0f;
            for (int t = 0; t < localSize; t++) {
                blockSum += lShared[t] * corrShared[t];
            }
            bcast[0] = blockSum;
        }
        context.localBarrier();
        float L = bcast[0];

        // Write UNNORMALIZED partial numerator (relative to block max M), plus M and L for the
        // combine.
        for (int d = tid; d < headSize; d += localSize) {
            float acc = 0.0f;
            for (int t = 0; t < localSize; t++) {
                acc += corrShared[t] * accShared[t * headSize + d];
            }
            att.set(outBase + d, acc); // unnormalized partial numerator (relative to block max M)
        }
        if (tid == 0) {
            att.set(mBase + s, M);
            att.set(lBase + s, L);
        }
    }

    // @formatter:off
    /**
     * Lane-cooperative split-KV attention for a 128-wide head over an FP16 paged cache.
     *
     * <p>Same mathematics, same paged addressing and the same partial-output layout as {@link
     * #processHeadsFlashAttentionSplitKVFP16Paged}, so {@code combineSplitKVAttention} reads it
     * unchanged. What differs is who owns what.
     *
     * <h2>Work distribution</h2>
     *
     * <p>The kernel it replaces parallelises over <b>key positions only</b>: one thread takes one
     * key and computes that key's entire 128-wide dot product and its entire 128-wide value
     * accumulation alone. Every thread therefore needs a private 128-float accumulator, and 64 of
     * them is 32 KiB of shared memory per block — 96% of that kernel's 34052-byte allocation, which
     * caps it at three blocks per SM and six resident warps of a possible 48. Those rows are {@code
     * headSize} floats apart and {@code 128 % 32 == 0}, so every lane of a warp addresses the same
     * shared-memory bank on every one of the 256 accesses each key costs.
     *
     * <p>This one parallelises over <b>both</b>. A warp owns a strided subset of one split's keys;
     * within a key all 32 lanes cooperate. Lane {@code L} owns head dimensions {@code 2L}, {@code
     * 2L+1}, {@code 64+2L} and {@code 64+2L+1} — four dimensions, held in four named FP32 scalars,
     * which the compiler keeps in registers because they are scalars and not an array it would have
     * to spill. The query is four more scalars. Nothing per-key touches shared memory.
     *
     * <p>That pairing of dimensions is for coalescing: at {@code 2L} the warp's 32 {@code Half2}
     * loads cover halves 0..63 of the key in one 128-byte transaction, and at {@code 64+2L} the
     * other half.
     *
     * <p>Shared memory is used once, after the loop, to fold the warps' partial results together:
     * {@code MAX_WARPS * 128} numerator floats plus a maximum and a denominator per warp. At four
     * warps that is 2084 bytes against the replaced kernel's 34052.
     *
     * <h2>The reduction</h2>
     *
     * <p>Each lane's four products are folded by the five-step {@code simdShuffleDown} butterfly
     * this codebase already uses for its FP16 matrix-vector kernels, which leaves the total in lane
     * zero, and {@code simdBroadcastFirst} returns it to every lane — every lane needs the score,
     * because every lane rescales its own accumulator by it. Six shuffles per key replace three
     * barrier-fenced serial loops over 64 shared floats. The shuffles are warp-scoped in hardware,
     * so several warps in one block do not interfere.
     *
     * <p>Lane divergence would depopulate them, so there is none: {@code startPos} and {@code
     * endPos} depend only on the group, every lane of a warp runs the same trip count, and the
     * early return is uniform across the block.
     *
     * <h2>Contracts this must not change</h2>
     *
     * <ul>
     *   <li><b>Online softmax</b> in FP32, rescaling numerator and denominator together, with the
     *       {@code m == -inf} guard so the first key never evaluates {@code exp(-inf - -inf)}. The
     *       cross-warp fold repeats the same guard for a warp that received no keys.
     *   <li><b>Empty splits</b> — a split past the end of the sequence runs no iterations in any
     *       warp and writes numerator 0, {@code M = -inf} and {@code L = 0}, which the combine
     *       reads as weight zero. Writing a finite zero rather than leaving the slot alone is what
     *       keeps {@code 0 * NaN} out of the combine.
     *   <li><b>Paged addressing, KV slot, GQA mapping and positionHolder</b> are the same calls
     *       against the same block table, so no unallocated page is touched and no key past {@code
     *       pos} is included.
     * </ul>
     *
     * <p>Requires {@code headSize == 128} and a workgroup that is a whole number of warps, at most
     * {@code MAX_WARPS}. The caller checks both; there is no fallback inside the kernel because a
     * wrong grid would be silent rather than fatal.
     */
    // @formatter:on
    public static void processHeadsFlashAttentionSplitKVFP16PagedLaneHead128(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray att,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int nSplits) {

        final int MAX_WARPS = 16;
        final int HEAD = 128;

        int tid = context.localIdx;
        int blockSize = context.localGroupSizeX;
        int lane = tid & 31;
        int warp = tid >> 5;
        int nWarps = blockSize >> 5;

        int g = context.groupIdx;
        int h = g / nSplits;
        int s = g % nSplits;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int seqLen = pos + 1;
        int chunk = (seqLen + nSplits - 1) / nSplits;
        int startPos = s * chunk;
        int endPos = Math.min(startPos + chunk, seqLen); // exclusive

        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        float invSqrt = 1.0f / TornadoMath.sqrt(headSize);

        int dA = lane * 2;
        int dB = 64 + lane * 2;

        int qBase = h * headSize;
        float q0 = q.get(qBase + dA);
        float q1 = q.get(qBase + dA + 1);
        float q2 = q.get(qBase + dB);
        float q3 = q.get(qBase + dB + 1);

        float[] partial = context.allocateFloatLocalArray(MAX_WARPS * HEAD);
        float[] mShared = context.allocateFloatLocalArray(MAX_WARPS);
        float[] lShared = context.allocateFloatLocalArray(MAX_WARPS);

        float acc0 = 0.0f;
        float acc1 = 0.0f;
        float acc2 = 0.0f;
        float acc3 = 0.0f;
        float m = Float.NEGATIVE_INFINITY;
        float l = 0.0f;

        for (int p = startPos + warp; p < endPos; p += nWarps) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, p, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;

            Half2 kA = key_cache.getHalf2(base + dA);
            Half2 kB = key_cache.getHalf2(base + dB);
            float part =
                    q0 * Half2.lowFloat(kA)
                            + q1 * Half2.highFloat(kA)
                            + q2 * Half2.lowFloat(kB)
                            + q3 * Half2.highFloat(kB);

            part += context.simdShuffleDown(part, 16);
            part += context.simdShuffleDown(part, 8);
            part += context.simdShuffleDown(part, 4);
            part += context.simdShuffleDown(part, 2);
            part += context.simdShuffleDown(part, 1);
            float score = context.simdBroadcastFirst(part) * invSqrt;

            float newM = Math.max(m, score);
            float corr = (m == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(m - newM);
            float e = TornadoMath.exp(score - newM);

            Half2 vA = value_cache.getHalf2(base + dA);
            Half2 vB = value_cache.getHalf2(base + dB);
            acc0 = acc0 * corr + e * Half2.lowFloat(vA);
            acc1 = acc1 * corr + e * Half2.highFloat(vA);
            acc2 = acc2 * corr + e * Half2.lowFloat(vB);
            acc3 = acc3 * corr + e * Half2.highFloat(vB);
            l = l * corr + e;
            m = newM;
        }

        int warpBase = warp * HEAD;
        partial[warpBase + dA] = acc0;
        partial[warpBase + dA + 1] = acc1;
        partial[warpBase + dB] = acc2;
        partial[warpBase + dB + 1] = acc3;
        if (lane == 0) {
            mShared[warp] = m;
            lShared[warp] = l;
        }
        context.localBarrier();

        int headBase = h * nSplits * (headSize + 2);
        int outBase = headBase + s * headSize;
        int mBase = headBase + nSplits * headSize;
        int lBase = mBase + nSplits;

        float blockMax = Float.NEGATIVE_INFINITY;
        for (int w = 0; w < nWarps; w++) {
            float mw = mShared[w];
            if (mw > blockMax) {
                blockMax = mw;
            }
        }
        float denom = 0.0f;
        for (int w = 0; w < nWarps; w++) {
            float mw = mShared[w];
            float f = (mw == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(mw - blockMax);
            denom += f * lShared[w];
        }

        for (int d = tid; d < headSize; d += blockSize) {
            float sum = 0.0f;
            for (int w = 0; w < nWarps; w++) {
                float mw = mShared[w];
                float f = (mw == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(mw - blockMax);
                sum += f * partial[w * HEAD + d];
            }
            att.set(outBase + d, sum);
        }
        if (tid == 0) {
            att.set(mBase + s, blockMax);
            att.set(lBase + s, denom);
        }
    }

    public static void processHeadsFlashAttentionSplitKVFP16Paged(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray att,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int nSplits) {

        final int MAX_HEAD_SIZE = 128;
        final int MAX_LOCAL_SIZE = 64;

        int tid = context.localIdx;
        int g = context.groupIdx; // 0 .. nHeads*nSplits - 1
        int localSize = context.localGroupSizeX;
        int h = g / nSplits;
        int s = g % nSplits;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int seqLen = pos + 1;
        int chunk = (seqLen + nSplits - 1) / nSplits;
        int startPos = s * chunk;
        int endPos = Math.min(startPos + chunk, seqLen); // exclusive

        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        float invSqrt = 1.0f / TornadoMath.sqrt(headSize);

        float[] q_shared = context.allocateFloatLocalArray(MAX_HEAD_SIZE);
        float[] accShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE * MAX_HEAD_SIZE);
        float[] mShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] lShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] corrShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] bcast = context.allocateFloatLocalArray(1);

        int headBase = h * nSplits * (headSize + 2);
        int outBase = headBase + s * headSize;
        int mBase = headBase + nSplits * headSize;
        int lBase = mBase + nSplits;

        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }
        int rowBase = tid * headSize;
        for (int d = 0; d < headSize; d++) {
            accShared[rowBase + d] = 0.0f;
        }
        context.localBarrier();

        // Strided scan over this split's position chunk (no barriers).
        float m = Float.NEGATIVE_INFINITY;
        float l = 0.0f;
        for (int p = startPos + tid; p < endPos; p += localSize) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, p, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;
            float score = 0.0f;
            for (int d = 0; d < headSize; d += 2) {
                Half2 kPair = key_cache.getHalf2(base + d);
                score += q_shared[d] * Half2.lowFloat(kPair);
                score += q_shared[d + 1] * Half2.highFloat(kPair);
            }
            score *= invSqrt;
            float newM = Math.max(m, score);
            float corr = (m == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(m - newM);
            float e = TornadoMath.exp(score - newM);
            for (int d = 0; d < headSize; d += 2) {
                Half2 vPair = value_cache.getHalf2(base + d);
                accShared[rowBase + d] = accShared[rowBase + d] * corr + e * Half2.lowFloat(vPair);
                accShared[rowBase + d + 1] =
                        accShared[rowBase + d + 1] * corr + e * Half2.highFloat(vPair);
            }
            l = l * corr + e;
            m = newM;
        }
        mShared[tid] = m;
        lShared[tid] = l;
        context.localBarrier();

        // Block max.
        if (tid == 0) {
            float blockMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < localSize; t++) {
                if (mShared[t] > blockMax) {
                    blockMax = mShared[t];
                }
            }
            bcast[0] = blockMax;
        }
        context.localBarrier();
        float M = bcast[0];

        corrShared[tid] =
                (mShared[tid] == Float.NEGATIVE_INFINITY)
                        ? 0.0f
                        : TornadoMath.exp(mShared[tid] - M);
        context.localBarrier();

        // Block sum L = Σ_t l_t · corr_t.
        if (tid == 0) {
            float blockSum = 0.0f;
            for (int t = 0; t < localSize; t++) {
                blockSum += lShared[t] * corrShared[t];
            }
            bcast[0] = blockSum;
        }
        context.localBarrier();
        float L = bcast[0];

        // Write UNNORMALIZED partial numerator (relative to block max M), plus M and L for the
        // combine.
        for (int d = tid; d < headSize; d += localSize) {
            float acc = 0.0f;
            for (int t = 0; t < localSize; t++) {
                acc += corrShared[t] * accShared[t * headSize + d];
            }
            att.set(outBase + d, acc);
        }
        if (tid == 0) {
            att.set(mBase + s, M);
            att.set(lBase + s, L);
        }
    }

    // @formatter:off
    /**
     * {@link #processHeadsFlashAttentionSplitKVFP16Paged} for a head twice as wide.
     *
     * <p>Identical body, identical algorithm, identical FP16 key/value interpretation. The only
     * difference is the pair of constants that size the shared arrays, and they are the reason a
     * separate method exists: {@code accShared} is {@code MAX_LOCAL_SIZE * MAX_HEAD_SIZE} floats,
     * so the 128-wide kernel's 64 x 128 cannot be handed a 256-wide head — it would read and write
     * past the array. This one is <b>32 x 256</b>, the same 32 KiB, so the wider head costs no more
     * shared memory; what it costs is half the lanes per workgroup, which the splits give back many
     * times over.
     *
     * <p><b>The workgroup must therefore be launched with at most 32 lanes</b>, because {@code
     * mShared}, {@code lShared} and {@code corrShared} are indexed by {@code localIdx} and both
     * block reductions run to {@code localGroupSizeX}. Everything else — the strided query stage,
     * the position scan, the running max and sum, and the strided partial write — is written
     * against {@code headSize} and {@code localSize} and needs no change.
     *
     * <p>The partial layout is the one {@code combineSplitKVAttention} expects, unchanged: per head
     * {@code nSplits * headSize} numerators, then {@code nSplits} maxima, then {@code nSplits}
     * sums. That combine is already generic in {@code headSize} and already treats a split whose
     * chunk was empty as a zero contribution.
     */
    // @formatter:on
    public static void processHeadsFlashAttentionSplitKVFP16PagedWideHead(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray att,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int nSplits) {

        final int MAX_HEAD_SIZE = 256;
        final int MAX_LOCAL_SIZE = 32;

        int tid = context.localIdx;
        int g = context.groupIdx; // 0 .. nHeads*nSplits - 1
        int localSize = context.localGroupSizeX;
        int h = g / nSplits;
        int s = g % nSplits;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int seqLen = pos + 1;
        int chunk = (seqLen + nSplits - 1) / nSplits;
        int startPos = s * chunk;
        int endPos = Math.min(startPos + chunk, seqLen); // exclusive

        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        float invSqrt = 1.0f / TornadoMath.sqrt(headSize);

        float[] q_shared = context.allocateFloatLocalArray(MAX_HEAD_SIZE);
        float[] accShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE * MAX_HEAD_SIZE);
        float[] mShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] lShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] corrShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] bcast = context.allocateFloatLocalArray(1);

        int headBase = h * nSplits * (headSize + 2);
        int outBase = headBase + s * headSize;
        int mBase = headBase + nSplits * headSize;
        int lBase = mBase + nSplits;

        for (int i = tid; i < headSize; i += localSize) {
            q_shared[i] = q.get(h * headSize + i);
        }
        int rowBase = tid * headSize;
        for (int d = 0; d < headSize; d++) {
            accShared[rowBase + d] = 0.0f;
        }
        context.localBarrier();

        // Strided scan over this split's position chunk (no barriers).
        float m = Float.NEGATIVE_INFINITY;
        float l = 0.0f;
        for (int p = startPos + tid; p < endPos; p += localSize) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, p, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;
            float score = 0.0f;
            for (int d = 0; d < headSize; d += 2) {
                Half2 kPair = key_cache.getHalf2(base + d);
                score += q_shared[d] * Half2.lowFloat(kPair);
                score += q_shared[d + 1] * Half2.highFloat(kPair);
            }
            score *= invSqrt;
            float newM = Math.max(m, score);
            float corr = (m == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(m - newM);
            float e = TornadoMath.exp(score - newM);
            for (int d = 0; d < headSize; d += 2) {
                Half2 vPair = value_cache.getHalf2(base + d);
                accShared[rowBase + d] = accShared[rowBase + d] * corr + e * Half2.lowFloat(vPair);
                accShared[rowBase + d + 1] =
                        accShared[rowBase + d + 1] * corr + e * Half2.highFloat(vPair);
            }
            l = l * corr + e;
            m = newM;
        }
        mShared[tid] = m;
        lShared[tid] = l;
        context.localBarrier();

        // Block max.
        if (tid == 0) {
            float blockMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < localSize; t++) {
                if (mShared[t] > blockMax) {
                    blockMax = mShared[t];
                }
            }
            bcast[0] = blockMax;
        }
        context.localBarrier();
        float M = bcast[0];

        corrShared[tid] =
                (mShared[tid] == Float.NEGATIVE_INFINITY)
                        ? 0.0f
                        : TornadoMath.exp(mShared[tid] - M);
        context.localBarrier();

        // Block sum L = Σ_t l_t · corr_t.
        if (tid == 0) {
            float blockSum = 0.0f;
            for (int t = 0; t < localSize; t++) {
                blockSum += lShared[t] * corrShared[t];
            }
            bcast[0] = blockSum;
        }
        context.localBarrier();
        float L = bcast[0];

        // Write UNNORMALIZED partial numerator (relative to block max M), plus M and L for the
        // combine.
        for (int d = tid; d < headSize; d += localSize) {
            float acc = 0.0f;
            for (int t = 0; t < localSize; t++) {
                acc += corrShared[t] * accShared[t * headSize + d];
            }
            att.set(outBase + d, acc);
        }
        if (tid == 0) {
            att.set(mBase + s, M);
            att.set(lBase + s, L);
        }
    }

    public static void processHeadsFlashAttentionSplitKVFP16PackedPaged(
            KernelContext context,
            FloatArray q,
            HalfFloatArray key_cache,
            HalfFloatArray value_cache,
            FloatArray att,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray positionHolder,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int nSplits) {

        final int MAX_HEAD_SIZE = 128;
        final int MAX_LOCAL_SIZE = 64;

        int tid = context.localIdx;
        int g = context.groupIdx; // 0 .. nHeads*nSplits - 1
        int localSize = context.localGroupSizeX;
        int h = g / nSplits;
        int s = g % nSplits;

        if (h >= nHeads) {
            return;
        }

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int seqLen = pos + 1;
        int chunk = (seqLen + nSplits - 1) / nSplits;
        int startPos = s * chunk;
        int endPos = Math.min(startPos + chunk, seqLen); // exclusive

        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        float invSqrt = 1.0f / TornadoMath.sqrt(headSize);

        Half2[] qPacked = context.allocateHalf2LocalArray(MAX_HEAD_SIZE / 2);
        float[] accShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE * MAX_HEAD_SIZE);
        float[] mShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] lShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] corrShared = context.allocateFloatLocalArray(MAX_LOCAL_SIZE);
        float[] bcast = context.allocateFloatLocalArray(1);

        int headBase = h * nSplits * (headSize + 2);
        int outBase = headBase + s * headSize;
        int mBase = headBase + nSplits * headSize;
        int lBase = mBase + nSplits;

        // Stage Q once as packed FP16 pairs; the per-pair conversion cost is paid once per
        // workgroup instead of the score loop paying two half->float expansions per K pair.
        for (int i = tid; i < headSize / 2; i += localSize) {
            qPacked[i] =
                    Half2.fromFloats(q.get(h * headSize + i * 2), q.get(h * headSize + i * 2 + 1));
        }
        int rowBase = tid * headSize;
        for (int d = 0; d < headSize; d++) {
            accShared[rowBase + d] = 0.0f;
        }
        context.localBarrier();

        // Strided scan over this split's position chunk (no barriers).
        float m = Float.NEGATIVE_INFINITY;
        float l = 0.0f;
        for (int p = startPos + tid; p < endPos; p += localSize) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, p, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;
            // Packed K·Q: one 32-bit load + one __hfma2 per pair; the two FP16 lane sums
            // (over headSize/2 <= 64 terms each) are expanded to FP32 once per row.
            Half2 scoreAcc = Half2.fromFloats(0.0f, 0.0f);
            for (int d = 0; d < headSize; d += 2) {
                scoreAcc = Half2.fma(key_cache.getHalf2(base + d), qPacked[d >> 1], scoreAcc);
            }
            float score = (Half2.lowFloat(scoreAcc) + Half2.highFloat(scoreAcc)) * invSqrt;
            float newM = Math.max(m, score);
            float corr = (m == Float.NEGATIVE_INFINITY) ? 0.0f : TornadoMath.exp(m - newM);
            float e = TornadoMath.exp(score - newM);
            for (int d = 0; d < headSize; d += 2) {
                Half2 vPair = value_cache.getHalf2(base + d);
                accShared[rowBase + d] = accShared[rowBase + d] * corr + e * Half2.lowFloat(vPair);
                accShared[rowBase + d + 1] =
                        accShared[rowBase + d + 1] * corr + e * Half2.highFloat(vPair);
            }
            l = l * corr + e;
            m = newM;
        }
        mShared[tid] = m;
        lShared[tid] = l;
        context.localBarrier();

        // Block max.
        if (tid == 0) {
            float blockMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < localSize; t++) {
                if (mShared[t] > blockMax) {
                    blockMax = mShared[t];
                }
            }
            bcast[0] = blockMax;
        }
        context.localBarrier();
        float M = bcast[0];

        corrShared[tid] =
                (mShared[tid] == Float.NEGATIVE_INFINITY)
                        ? 0.0f
                        : TornadoMath.exp(mShared[tid] - M);
        context.localBarrier();

        // Block sum L = Σ_t l_t · corr_t.
        if (tid == 0) {
            float blockSum = 0.0f;
            for (int t = 0; t < localSize; t++) {
                blockSum += lShared[t] * corrShared[t];
            }
            bcast[0] = blockSum;
        }
        context.localBarrier();
        float L = bcast[0];

        // Write UNNORMALIZED partial numerator (relative to block max M), plus M and L for the
        // combine.
        for (int d = tid; d < headSize; d += localSize) {
            float acc = 0.0f;
            for (int t = 0; t < localSize; t++) {
                acc += corrShared[t] * accShared[t * headSize + d];
            }
            att.set(outBase + d, acc);
        }
        if (tid == 0) {
            att.set(mBase + s, M);
            att.set(lBase + s, L);
        }
    }

    public static void processHeadsParallelPaged(
            FloatArray q,
            FloatArray key_cache,
            FloatArray value_cache,
            FloatArray xb,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int seqLen,
            IntArray positionHolder,
            FloatArray wrapAtt,
            int layer,
            IntArray blockTable,
            int blockCfg,
            int blockStride) {

        int pos = positionHolder.get(0);
        int slot = positionHolder.get(1);
        int layerOff = KvBlockAddress.layerOffset(layer, kvDim, blockCfg);

        // Parallelize computation across attention heads
        for (@Parallel int h = 0; h < nHeads; h++) {
            // Process each head in parallel
            processHeadTornadoPaged(
                    q,
                    key_cache,
                    value_cache,
                    xb,
                    h,
                    headSize,
                    kvDim,
                    kvMul,
                    blockTable,
                    slot,
                    layerOff,
                    blockCfg,
                    blockStride,
                    pos,
                    wrapAtt);
        }
    }

    private static void processHeadTornadoPaged(
            FloatArray allQ,
            FloatArray key_cache,
            FloatArray value_cache,
            FloatArray allXb,
            int h,
            int headSize,
            int kvDim,
            int kvMul,
            IntArray blockTable,
            int slot,
            int layerOff,
            int blockCfg,
            int blockStride,
            int pos,
            FloatArray wrapAtt) {

        // Base index for this head's attention weights
        int headOffset = h * (pos + 1);

        // STEP 1: Calculate attention scores for all timesteps
        for (int t = 0; t <= pos; t++) {
            int kvHeadIdx = h / kvMul;
            int keyOffset =
                    KvBlockAddress.offset(
                                    blockTable, slot, t, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;

            float score = 0.0f;
            for (int i = 0; i < headSize; i++) {
                score += allQ.get(h * headSize + i) * key_cache.get(keyOffset + i);
            }
            score = score / TornadoMath.sqrt(headSize);

            // Store in attention buffer
            wrapAtt.set(headOffset + t, score);
        }

        // STEP 2: Find max score for softmax stability
        float maxScore = wrapAtt.get(headOffset);
        for (int t = 1; t <= pos; t++) {
            float val = wrapAtt.get(headOffset + t);
            if (val > maxScore) {
                maxScore = val;
            }
        }

        // STEP 3: Compute exponentials and sum
        float sum = 0.0f;
        for (int t = 0; t <= pos; t++) {
            int idx = headOffset + t;
            float expScore = TornadoMath.exp(wrapAtt.get(idx) - maxScore);
            wrapAtt.set(idx, expScore);
            sum += expScore;
        }

        // STEP 4: Normalize
        float normFactor = (sum > 0.0f) ? (1.0f / sum) : (1.0f / (pos + 1));
        for (int t = 0; t <= pos; t++) {
            int idx = headOffset + t;
            wrapAtt.set(idx, wrapAtt.get(idx) * normFactor);
        }

        // STEP 5: Compute weighted sum of values for each dimension
        //
        // The loop nest is t-outer here where the legacy kernel had i-outer, and the accumulator
        // array is what makes that safe: element i still sums over t in ascending order, so the
        // floating-point result is identical. The reason to swap is the block walk — it depends on
        // t and not on i, and i-outer would repeat it headSize times per position. That cost is
        // what made Mistral -3.8% while every other family sat under 1%.
        int kvHeadIdx = h / kvMul;
        float[] weightedSums = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            weightedSums[i] = 0.0f;
        }
        for (int t = 0; t <= pos; t++) {
            int valueOffset =
                    KvBlockAddress.offset(
                                    blockTable, slot, t, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadIdx * headSize;
            float attWeight = wrapAtt.get(headOffset + t);
            for (int i = 0; i < headSize; i++) {
                weightedSums[i] += attWeight * value_cache.get(valueOffset + i);
            }
        }
        for (int i = 0; i < headSize; i++) {
            allXb.set(h * headSize + i, weightedSums[i]);
        }
    }
}
