spring.ai.jitllm.chat.model-path=${MODEL}
spring.ai.jitllm.chat.on-gpu=true
spring.ai.jitllm.chat.context-length=4096
spring.ai.jitllm.chat.temperature=0.0
spring.ai.jitllm.chat.max-tokens=512
spring.main.banner-mode=off
logging.level.root=warn
